kitchen/urls.py
from django.urls import path

from kitchen.views import (index,
                           DishTypeListView,
                           DishTypeCreateView,
                           DishTypeUpdateView,
                           DishTypeDeleteView,
                           DishCreateView,
                           DishUpdateView,
                           DishDeleteView,
                           DishListView,
                           DishDetailView,
                           CookListView,
                           CookDetailView,
                           CookCreateView,
                           toggle_assign_to_dish,
                           CookUpdateView,
                           CookDeleteView
                           )


urlpatterns = [
    path("", index, name="index"),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),

]

app_name = "kitchen"

this_is_kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),

    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
{% block footer %}
     <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            {% if request.path == '/' %}
              <p class="text-justify">You have visited this page {{ request.session.num_visits }} time{{ request.session.num_visits|pluralize }}.</p>
            {% endif %}
            Just a footer
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick</h6>
            <ul class="footer-links">
              <li><a href="{% url 'kitchen:index' %}">Home</a></li>
              <li><a href="{% url 'kitchen:cook-list' %}">Cooks</a></li>

            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Links</h6>
            <ul class="footer-links">
              <li><a href="{% url 'kitchen:dish-list' %}">Dishes</a></li>
              <li><a href="{% url 'kitchen:dish-type-list' %}">Dish types</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Some Copyright &copy; information
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="linkedin" href="https://www.linkedin.com/in/anatolii-pozniak-84b235273/"><i class="fab fa-linkedin"></i></a></li>
              <li><a class="github" href="https://github.com/Anatolii-Poznyak"><i class="fab fa-github"></i></a></li>
              <li><a class="telegram" href="https://t.me/Anatoliipozniak"><i class="fab fa-telegram"></i></a></li>
              <li><a class="youtube" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"><i class="fab fa-youtube"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
{% endblock %}

templates/includes/pagination.html
{% load query_transform %}
{% block pagination %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="btn btn-outline-primary">prev</a>
        </li>
      {% endif %}

      <li class="page-item active">
        <span class="btn btn-outline-primary">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="btn btn-outline-primary">next</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}

templates/includes/sidebar.html
<nav role="navigation">
  <div id="menuToggle">

    <input type="checkbox" />

    <span></span>
    <span></span>
    <span></span>

    <ul id="menu">
      {% if user.is_authenticated %}
        User: <a href="{{ user.get_absolute_url }}"><li>{{ user.get_username }}</li></a>
        <a href="{% url 'logout'%}?next={{request.path}}"><li>Logout</li></a>
      {% else %}
        <a href="{% url 'login'%}?next={{request.path}}"><li>Login</li></a>
      {% endif %}
      <a href="{% url 'kitchen:index' %}"><li>Home</li></a>
      <a href="{% url 'kitchen:cook-list' %}"><li>Cooks</li></a>
      <a href="{% url 'kitchen:dish-list' %}"><li>Dishes</li></a>
      <a href="{% url 'kitchen:dish-type-list' %}"><li>Dish Types</li></a>
    </ul>
  </div>
</nav>