kitchen/urls.py
from django.urls import path

from kitchen.views import (index,
                           DishTypeListView,
                           DishTypeCreateView,
                           DishTypeUpdateView,
                           DishTypeDeleteView,
                           DishCreateView,
                           DishUpdateView,
                           DishDeleteView,
                           DishListView,
                           DishDetailView,
                           CookListView,
                           CookDetailView,
                           CookCreateView,
                           toggle_assign_to_dish,
                           CookUpdateView,
                           CookDeleteView
                           )


urlpatterns = [
    path("", index, name="index"),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),

]

app_name = "kitchen"

this_is_kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),

    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ["username"]
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(
        to=DishType,
        on_delete=models.CASCADE,
        related_name="dishes",
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes",
        blank=True
    )

    class Meta:
        ordering = ["name"]
        verbose_name = "dish"
        verbose_name_plural = "dishes"

    def __str__(self):
        return f"{self.name} (price: {self.price}, type: {self.dish_type.name})"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Cook, Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience"
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "years_of_experience"
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


def validate_years_of_experience(years_of_experience):
    if years_of_experience < 0 or years_of_experience > 100:
        raise ValidationError("Please, enter a valid number")
    return years_of_experience


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class SearchForm(forms.Form):
    title = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name ..."})
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import DishForm, CookCreationForm, SearchForm, CookUpdateForm
from kitchen.models import Dish, Cook, DishType


@login_required
def index(request):
    num_dishes = Dish.objects.count()
    num_cooks = Cook.objects.count()
    num_dish_types = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_dishes": num_dishes,
        "num_cooks": num_cooks,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits + 1,

    }
    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 5
    queryset = DishType.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()

        title = self.request.GET.get("title", "")
        context["search_form"] = SearchForm(initial={
            "title": title
        })
        return context

    def get_queryset(self):

        form = SearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()

        name = self.request.GET.get("title", "")
        context["search_form"] = SearchForm(initial={
            "title": name
        })
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")

        form = SearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["title"]
            )

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()

        name = self.request.GET.get("title", "")
        context["search_form"] = SearchForm(initial={
            "title": name
        })
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()

        form = SearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["title"]
            )

        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__dish_type")
    paginate_by = 5



class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if (
        Dish.objects.get(id=pk) in cook.dishes.all()
    ):
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}
{% block title %}<title>Delete | This is Kitchen</title>{% endblock %}
{% block content %}
  <h2>Delete Dish Type</h2>

  <p>Are you sure you want to delete the cook {{ cook }}?</p>

  <form action="" method="post">
  {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-outline-danger">
    <a href="javascript:history.back()" class="btn btn-outline-dark">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}
{% block title %}<title>Info | This is Kitchen</title>{% endblock %}
{% block content %}
  <h1>
    Username: {{ cook.username }}
  </h1>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Email:</strong> {{ cook.email }}</p>
  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>

  <div>
    <h4>Dishes</h4>

    <table class="table">
      <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Price</th>
      <th>Type</th>
      </tr>

      {% for dish in cook.dishes.all %}
        <tr>
          <td>
            {{ dish.id }}
          </td>
          <td>
            <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
          </td>
          <td>
            {{ dish.price }}
          </td>
          <td>
            {{ dish.dish_type }}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}
{% block create_button %}
  <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" id="delete" class="btn btn-outline-danger link-to-page">
      Delete
    </a>

    <a  href="{% url 'kitchen:cook-update' pk=cook.id %}" id="update" class="btn btn-outline-primary link-to-page">
      Update
    </a>
  <a class="btn btn-outline-primary" id="create" href="{% url 'kitchen:cook-create' %}">Create</a>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>{{ object|yesno:"Update,Create" }} | This Kitchen</title>{% endblock %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Cook</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-outline-primary">
  <a href="javascript:history.back()" class="btn btn-outline-dark">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>Cooks | This is Kitchen</title>{% endblock %}


{% block content %}
    <h1>
      Cook List

    </h1>

    <form  action="" method="get">
      {{ search_form|crispy }}
     <input id="searchform" type="submit" value="Search" class="btn btn-outline-primary" >
    </form>

    {% if cook_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
        <th>Email</th>
        <th>Last activity</th>
      </tr>
    {% for cook in cook_list %}
      <tr>
        <td>{{ cook.id }}</td>
        <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
        <td>{{ cook.first_name }}</td>
        <td>{{ cook.last_name }}</td>
        <td>{{ cook.years_of_experience|default_if_none:"" }}</td>
        <td>{{ cook.email }}</td>
        <td>{{ cook.last_login|default_if_none:"" }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no cook in the service yet!</p>
    {% endif %}
{% endblock %}
{% block sidebar %}
  {% include "includes/sidebar.html" %}

{% endblock %}
{% block create_button %}
  <a class="btn btn-outline-primary" id="create" href="{% url 'kitchen:cook-create' %}">Create</a>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}
{% block title %}<title>Delete | This is Kitchen</title>{% endblock %}
{% block content %}
  <h2>Delete Dish Type</h2>

  <p>Are you sure you want to delete the dish {{ dish.name }}?</p>

  <form action="" method="post">
  {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-outline-danger">
    <a href="javascript:history.back()" class="btn btn-outline-dark">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}
{% block title %}<title>Info | This is Kitchen</title>{% endblock %}
{% block content %}
  <h1>
    {{ dish.name }}
  </h1>
  <p>Dish type: {{ dish.dish_type.name }}</p>
  <hr>
  <h3>
    Cooks

  </h3>
  <hr>
  <ul>
    {% for cook in dish.cooks.all %}
     <li><a href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }}){% if user == cook %} (Me){% endif %}</a></li>
    {% endfor %}
  </ul>
{% endblock %}
{% block create_button %}
  <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" id="delete" class="btn btn-outline-danger link-to-page">
      Delete
    </a>

    <a  href="{% url 'kitchen:dish-update' pk=dish.id %}" id="update" class="btn btn-outline-primary link-to-page">
      Update
    </a>
  <a class="btn btn-outline-primary" id="create" href="{% url 'kitchen:dish-create' %}">Create</a>
  {% if dish in user.dishes.all %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" id="assign" class="btn btn-danger link-to-page">
        Delete me from this dish
      </a>
    {% else %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" id="assign" class="btn btn-success link-to-page">
        Assign me to this dish
      </a>
    {% endif %}
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>{{ object|yesno:"Update,Create" }} | This Kitchen</title>{% endblock %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}

    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-outline-primary">
  <a href="javascript:history.back()" class="btn btn-outline-dark">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>Dishes | This is Kitchen</title>{% endblock %}
{% block content %}
  <h1>
    Dish list
  </h1>

  <form action="" method="get">
    {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-outline-primary">
  </form>

  <br>

  {% if dish_list %}
    <table class="table">
      <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Price</th>
      <th>Type</th>
      </tr>

      {% for dish in dish_list %}
        <tr>
          <td>
            {{ dish.id }}
          </td>
          <td>
            <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
          </td>
          <td>
            {{ dish.price }}
          </td>
          <td>
            {{ dish.dish_type }}
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no dishes yet!</p>
  {% endif %}
{% endblock %}
{% block create_button %}
  <a class="btn btn-outline-primary" id="create" href="{% url 'kitchen:dish-create' %}">Create</a>
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}
{% block title %}<title>Delete | This is Kitchen</title>{% endblock %}
{% block content %}
  <h2>Delete Dish Type</h2>

  <p>Are you sure you want to delete the dish type: {{ dishtype }}?</p>
  <p>All Dishes with this dish-type will be also deleted!</p>

  <form action="" method="post">
  {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-outline-danger">
    <a href="javascript:history.back()" class="btn btn-outline-dark">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>{{ object|yesno:"Update,Create" }} | This Kitchen</title>{% endblock %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}

    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-outline-primary">
  <a href="javascript:history.back()" class="btn btn-outline-dark">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>Dish types | This is Kitchen</title>{% endblock %}
{% block content %}
  <h1>
    Dish Types
  </h1>

  <form action="" method="get">
      {{ search_form|crispy }}
     <input id="searchform" type="submit" value="Search" class="btn btn-outline-primary">
  </form>

  {% if dish_type_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for dish_type in dish_type_list %}
        <tr>
          <td>
              {{ dish_type.id }}
          </td>
          <td>
              {{ dish_type.name }}
          </td>
          <td>
              <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no dish types in the service.</p>
  {% endif %}
{% endblock %}
{% block create_button %}
  <a class="btn btn-outline-primary" id="create" href="{% url 'kitchen:dish-type-create' %}">Create</a>
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}


{% block content %}
  <h1>Welcome to the kitchen service!</h1>
  <p>The Kitchen service has the following record counts:</p>
  <hr>
<div class="container" >
  <div class="row">
    <div class="col-md-4" >
      <h1><span class="counter">{{ num_cooks }}</span></h1>
      <h3><a class="home-links" href="{% url 'kitchen:cook-list' %}">Cooks</a></h3>
      <i class="fa fa-users"></i>
    </div>
    <div class="col-md-4">
      <h1><span class="counter">{{ num_dishes }}</span></h1>
      <h3><a class="home-links" href="{% url 'kitchen:dish-list' %}">Total Number of Dishes</a></h3>
      <i class="far fa-hamburger"></i>
    </div>
    <div class="col-md-4">
      <h1><span class="counter">{{ num_dish_types }}</span></h1>
      <h3><a class="home-links" href="{% url 'kitchen:dish-type-list' %}">Dish Types</a></h3>
      <h3></h3>
      <i class="fas fa-bacon"></i>
    </div>
  </div>
</div>
{% endblock %}